version: '3.2'
services: 
  java: 
    image: openjdk:11
    container_name: medicine_audit_system
    tty: true 
    ports:
      - 8080:8080
    volumes:
      - .:/home
  db:
    build: 
      context: .
      dockerfile: ./development/postgresql/Dockerfile
    container_name: medicine_audit_development
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: 'medicine_audit_development'
      POSTGRES_PASSWORD: 'Makt0112'
    volumes:
      - ./develop_db:/docker-entrypoint-initdb.d
  