version: '3.2'
services: 
  java: 
    image: openjdk:11
    container_name: medicine_audit_system
    tty: true 
    ports:
      - 8080:8080
    volumes:
      - .:/home
    env_file:
      - .env
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - "./development/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medicine_audit_development
      - MYSQL_USER=poteto1212
      - MYSQL_PASSWORD=Makt0112
  mariadb_test: #テスト用のDBコンテナ
    image: mariadb
    ports:
      - 3307:3306
    volumes:
      - "./development/mariadb_test:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medicine_audit_development_test
      - MYSQL_USER=poteto1212
      - MYSQL_PASSWORD=Makt0112
