version: '3.2'
services: 
  java: 
    image: openjdk:11
    container_name: medicine_audit_system
    tty: true 
    ports:
      - 8080:8080
    volumes:
      - .:/home
    env_file:
      - .env
  db: #TODO　初期開発用に作ってただけ依存関係の移行次第消す
    build: 
      context: .
      dockerfile: ./development/postgresql/Dockerfile
    container_name: medicine_audit_development
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: 'medicine_audit_development'
      POSTGRES_PASSWORD: 'Makt0112'
    volumes:
      - ./develop_db:/docker-entrypoint-initdb.d
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - "./development/mariadb:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medicine_audit_development
      - MYSQL_USER=poteto1212
      - MYSQL_PASSWORD=Makt0112
